name: GenAI_project
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python=3.10  
  - pip
  - pip:
      - together
      - openai
      - pandas
      - numpy
      - matplotlib
      - python-dotenv
      - backoff
      - pyarrow
      - wandb
      - langchain-ollama
      - seaborn
      - scikit-learn